# Generated by Django 3.1.4 on 2020-12-08 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20201208_2115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['date_added']},
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='add_date',
            new_name='date_added',
        ),
    ]
